name: annotate_rsids_from_linker-env
dependencies:
  - zlib
  - bzip2
  - git
# required for commitizen
  - nodejs
  - pre-commit
  - cppcheck
  - sarcasm::clang-format


  - automake
  - autoconf
  - make>=4.2
  - gxx_linux-64>=8.2.0
